<#global 
	"MAPFIGHT" 			= "/player/mapFight.jsp"
	"MAPFIGHTREPORT" 	= "/player/mapFightReport.jsp"
	"ROOT" 				= "/"
	"CHARACTER" 		= "/player/character.html"
	"MAP" 				= "/player/map.jsp"
	"EQUIP" 			= "/player/equip.jsp"
	"SPELL" 			= "/player/spell.jsp"
	"SPELLBOOK" 		= "/player/spellbook.jsp"
	"STATUS" 			= "/player/status.jsp"
	"REGISTER" 			= "/login/register.jsp"
	"BATTLEPLAN"		= "/player/battleplan.jsp"
	"NPCDIALOG"			= "/player/npcdialog.jsp"
	"SHOP"				= "/player/shop.jsp"
	"SSHOP"				= "/player/sshop.jsp"
	"ADMIN_HOME" 		= "/admin/adminHome.jsp"
	"ADMIN_MAPPREVIEW" 	= "/admin/map/mapUtilPreview.jsp"
	"ADMIN_MAPUTIL" 	= "/admin/map/mapUtil.jsp"
	"ADMIN_MAPLIST" 	= "/admin/map/listArea.jsp"
	"ADMIN_MAPITEMS" 	= "/admin/map/mapItems.jsp"
/>
